-- ==========================================================================
-- This file is part of Briefing Room for DCS World, a mission
-- generator for DCS World, by @akaAgar (https://github.com/akaAgar/briefing-room-for-dcs)

-- Briefing Room for DCS World is free software: you can redistribute it
-- and/or modify it under the terms of the GNU General Public License
-- as published by the Free Software Foundation, either version 3 of
-- the License, or (at your option) any later version.

-- Briefing Room for DCS World is distributed in the hope that it will
-- be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
-- of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.

-- You should have received a copy of the GNU General Public License
-- along with Briefing Room for DCS World. If not, see https://www.gnu.org/licenses/
-- ==========================================================================

-- ===================================================================================
-- SUMMARY
-- ===================================================================================
-- 1 - Core functions
--   1.1 - Constants and initialization -- BRInit.lua
--   1.2 - Lua extensions -- LuaExtensions.lua
--     1.2.1 - Converters
--     1.2.2 - Math extensions
--     1.2.3 - String extensions
--     1.2.4 - Table extensions
--   1.3 - DCS World extensions -- DCSExtensions.lua
--   1.4 - MIST -- MIST.lua
-- 2 - Tools
--   2.1 - Radio manager -- RadioManager.lua
--   2.2 - Aircraft activator -- AircraftActivator.lua
--   2.3 - Event handler -- EventHandler.lua
--   2.4 - Transport Handler -- TransportManager.lua
-- 3 - Mission
--   3.1 - Main BriefingRoom table and core functions
--   3.2 - Common F10 menu
--   3.3 - Objectives tables (generated by BriefingRoom)
--   3.4 - Objectives triggers (generated by BriefingRoom)
--   3.5 - Script singletons (generated by BriefingRoom)
--   3.6 - Objectives features (generated by BriefingRoom)
--   3.7 - Mission features (generated by BriefingRoom)
--   3.8 - Startup -- Start.lua



-- ***********************************************************************************
-- * 3 - MISSION                                                                     *
-- ***********************************************************************************

-- ===================================================================================
-- 3.1 - MAIN BRIEFINGROOM TABLE AND CORE FUNCTIONS
-- ===================================================================================

briefingRoom.mission = {} -- Main BriefingRoom mission table
briefingRoom.mission.complete = false -- Is the mission complete?
briefingRoom.mission.coreFunctions = { }
briefingRoom.mission.hasStarted = false -- has at least one player taken off?
briefingRoom.mission.autoEnd = $ENDMISSIONAUTOMATICALLY$
briefingRoom.mission.commandEnd = $ENDMISSIONONCOMMAND$
briefingRoom.mission.MapMarkers = $SHOWMAPMARKERS$
briefingRoom.mission.objectiveDropDistanceMeters = $DROPOFFDISTANCEMETERS$

-- Marks objective with index index as complete, and completes the mission itself if all objectives are complete
function briefingRoom.mission.coreFunctions.completeObjective(index, failed)
  failed = failed or false
  local revealObjective = 0
  if briefingRoom.mission.complete then return end -- mission already complete
  if briefingRoom.mission.objectives[index].complete and briefingRoom.mission.objectives[index].failed == failed then return end -- objective already complete with same fail state

  local objName = briefingRoom.mission.objectives[index].name
  briefingRoom.debugPrint("Objective "..objName.." marked as "..(failed and "failed" or"complete"))
  briefingRoom.mission.objectives[index].complete = true
  briefingRoom.mission.objectives[index].failed = failed
  briefingRoom.aircraftActivator.pushFromReserveQueue() -- activate next batch of aircraft (so more CAP will pop up)
  for k,objective in pairs(briefingRoom.mission.objectives) do
    if objective ~= nil and objective.progressionHidden and briefingRoom.mission.coreFunctions.assesCondition(objective.progressionCondition) then
      local minsPassed = math.floor((timer.getAbsTime() - timer.getTime0())/60)
      objective.startMinutes = minsPassed
      local acGroup = Group.getByName(objective.groupName) -- get the group
      if acGroup ~= nil then -- activate the group, if it exists
        acGroup:activate()
        local Start = {
          id = 'Start',
          params = {
          }
        }
        acGroup:getController():setCommand(Start)
        briefingRoom.debugPrint("Activating objective group "..acGroup:getName())
        objective.progressionHidden = false
      else
        briefingRoom.debugPrint("Failed to activate objective group "..objective.name)
      end
      if objective ~= nil and objective.progressionHiddenBrief then
        objective.progressionHiddenBrief = false
        briefingRoom.f10MenuCommands.activateObjective(k)
        if objective.waypoint ~= nil and briefingRoom.mission.MapMarkers then
          local vec3pos = dcsExtensions.toVec3(objective.waypoint)
          trigger.action.textToAll(briefingRoom.playerCoalition, k * 100 , vec3pos,{0, 0, 0, .53} , {1, 1, 1, .53} , 15, true , objective.name)
        end
        revealObjective = revealObjective + 1
      end
    end
  end
  

  -- Remove objective menu from the F10 menu
  if briefingRoom.f10Menu.objectives[index] ~= nil then
    missionCommands.removeItemForCoalition(briefingRoom.playerCoalition, briefingRoom.f10Menu.objectives[index])
    briefingRoom.f10Menu.objectives[index] = nil
  end

  -- Add a little delay before playing the "mission/objective complete" sounds to make sure all "target destroyed", "target photographed", etc. sounds are done playing
  local completeCount = 0
  for k,v in pairs(briefingRoom.mission.objectives) do
    if v.complete then
      completeCount = completeCount + 1
    end
  end
  local missionOver = completeCount >= table.count(briefingRoom.mission.objectives)
  -- Debug missions called complete early
  if briefingRoom.printDebugMessages then
    briefingRoom.debugPrint("Objective Completion state: "..tostring(completeCount).."/"..tostring(table.count(briefingRoom.mission.objectives)).."=".. tostring(missionOver))
  end
  -- End Debug
  if missionOver then
    briefingRoom.debugPrint("Mission marked as complete")
    briefingRoom.mission.complete = true
    local hasFailed = false

    for k,v in pairs(briefingRoom.mission.objectives) do
      if v.failed then
        hasFailed = true
      end
    end

    briefingRoom.radioManager.play("$LANG_COMMAND$: "..(hasFailed and "$LANG_MISSIONCOMPLETEWITHFAILURES$" or "$LANG_MISSIONCOMPLETE$"), (hasFailed and  "RadioHQMissionFailed" or "RadioHQMissionComplete"), math.random(6, 8))
    trigger.action.setUserFlag("BR_MISSION_COMPLETE", true) -- Mark the mission complete internally, so campaigns can move to the next mission
    if briefingRoom.mission.autoEnd then
      trigger.action.setUserFlag("BR_END_MISSION", true) -- Set off end mission trigger
    end
    if briefingRoom.mission.commandEnd then
      missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "$LANG_ENDMISSION$", nil, briefingRoom.f10MenuCommands.endMission, nil)
    end
  elseif not briefingRoom.mission.hasStarted then
    briefingRoom.radioManager.play("$LANG_AUTOCOMPLETEOBJECTIVE$", "Radio0", math.random(6, 8))
  else
    briefingRoom.radioManager.play("$LANG_COMMAND$: "..(failed and "$LANG_FAILEDOBJECTIVE$" or "$LANG_COMPLETEOBJECTIVE$"), (failed and "RadioHQObjectiveFailed" or "RadioHQObjectiveComplete"), math.random(6, 8))
    if revealObjective > 0 then 
      local time =  math.random(12, 15)
      for j = 1, revealObjective, 1 do
        if j > 1 then
          time = time + 4
        end
        briefingRoom.radioManager.play("$LANG_COMMAND$: $LANG_NEWOBJECTIVE$: "..briefingRoom.mission.objectives[index + j].task, "RadioHQNewObjective", time)
      end
    end
  end
end

function briefingRoom.mission.coreFunctions.assesCondition(condition)
    if condition == nil then return true end -- better to have a objective activate than not
    briefingRoom.debugPrint("Assessing raw condition: "..condition)
    local parsedCondition = string.gsub(condition, "(%d+)", "briefingRoom.mission.objectives[%1].complete == true")
    briefingRoom.debugPrint("Assessing parsed condition: "..parsedCondition)
    local f,err=loadstring("return "..parsedCondition)
    if f then
        return f()
    else
        briefingRoom.debugPrint("Condition Parsing Error: "..err)
        return true -- better to have a objective activate than not
    end
end

-- Begins the mission (called when the first player takes off)
function briefingRoom.mission.coreFunctions.beginMission()
  if briefingRoom.mission.hasStarted then return end -- mission has already started, do nothing

  briefingRoom.debugPrint("Mission has started")

  -- enable the aircraft activator and start spawning aircraft
  briefingRoom.mission.hasStarted = true
  timer.scheduleFunction(briefingRoom.aircraftActivator.update, nil, timer.getTime() + briefingRoom.aircraftActivator.getRandomInterval())
end

-- ===================================================================================
-- 3.2 - COMMON F10 MENU
-- ===================================================================================

-- Mission F10 menu hierarchy
briefingRoom.f10Menu = { }
briefingRoom.f10Menu.objectives = { }

 -- Mission F10 menu functions
briefingRoom.f10MenuCommands = { }
briefingRoom.f10MenuCommands.missionFeatures = { }

 -- Mission status menu
function briefingRoom.f10MenuCommands.missionStatus()
  local msnStatus = ""
  local msnSound = ""

  if briefingRoom.mission.complete then
    msnStatus = "$LANG_COMMAND$: Mission complete, you may return to base.\n\n"
    msnSound = "RadioHQMissionStatusComplete"
  else
    msnStatus = "$LANG_COMMAND$: Mission is still in progress.\n\n"
    msnSound = "RadioHQMissionStatusInProgress"
  end

  for i,o in ipairs(briefingRoom.mission.objectives) do
    if o.progressionHiddenBrief == false then
      if o.complete then
        msnStatus = msnStatus..(o.failed and "[/]" or "[X]")
      else
        msnStatus = msnStatus.."[ ]"
      end

      local objectiveProgress = ""
      if o.unitsCount > 0 and o.hideTargetCount ~= true then
        local targetsDone = math.max(0, o.unitsCount - table.count(o.unitNames))
        objectiveProgress = " ("..tostring(targetsDone).."/"..tostring(o.unitsCount)..")"
      end

      msnStatus = msnStatus.." "..o.task..objectiveProgress.."\n"
    end
  end

  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_MISSIONSTATUSREQUEST$", "RadioPilotMissionStatus")
  briefingRoom.radioManager.play(msnStatus, msnSound, briefingRoom.radioManager.getAnswerDelay())
end

function briefingRoom.f10MenuCommands.getWaypointCoordinates(index)
  local cooMessage = dcsExtensions.vec2ToStringCoordinates(briefingRoom.mission.objectives[index].waypoint)
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_WAYPOINTREQUEST$", "RadioPilotWaypointCoordinates")
  briefingRoom.radioManager.play("$LANG_COMMAND$: $LANG_WAYPOINTRESPONSE$\n\n"..cooMessage, "RadioHQWaypointCoordinates", briefingRoom.radioManager.getAnswerDelay())
  
  local idx = briefingRoom.mission.objectives[index].waypointRadioCommandIndex
  missionCommands.removeItemForCoalition(briefingRoom.playerCoalition, briefingRoom.mission.objectives[index].f10Commands[idx].commandPath)
  briefingRoom.mission.objectives[index].f10Commands[idx].commandPath = missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "$LANG_WAYPOINTCOORDINATES$:\n"..cooMessage, briefingRoom.f10Menu.objectives[index], briefingRoom.f10MenuCommands.getWaypointCoordinates, index)
end

function briefingRoom.f10MenuCommands.endMission ()
  trigger.action.setUserFlag("BR_END_MISSION_NOW", true)
end

function briefingRoom.f10MenuCommands.activateObjective(i)
  briefingRoom.f10Menu.objectives[i] = missionCommands.addSubMenuForCoalition(briefingRoom.playerCoalition,  briefingRoom.mission.objectives[i].f10MenuText, briefingRoom.f10Menu.objectiveMenu)
  for j=1,table.count(briefingRoom.mission.objectives[i].f10Commands) do
    briefingRoom.mission.objectives[i].f10Commands[j].commandPath = missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, briefingRoom.mission.objectives[i].f10Commands[j].text, briefingRoom.f10Menu.objectives[i] ,briefingRoom.mission.objectives[i].f10Commands[j].func, briefingRoom.mission.objectives[i].f10Commands[j].args)
  end
  if briefingRoom.printDebugMessages then
    missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "(DEBUG) Destroy target unit", briefingRoom.f10Menu.objectives[i] ,briefingRoom.f10MenuCommands.debug.destroySpecificTargetUnit, i)
  end
end

-- Common mission menu (mission status and mission features)
briefingRoom.f10Menu.missionMenu = missionCommands.addSubMenuForCoalition(briefingRoom.playerCoalition, "$LANG_MISSION$", nil)
missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "$LANG_MISSIONSTATUS$", briefingRoom.f10Menu.missionMenu, briefingRoom.f10MenuCommands.missionStatus, nil)

briefingRoom.f10Menu.objectiveMenu = missionCommands.addSubMenuForCoalition(briefingRoom.playerCoalition, "$LANG_OBJECTIVES$", nil)

-- ===================================================================================
-- 3.3 - OBJECTIVES TABLES (generated by BriefingRoom)
-- ===================================================================================

briefingRoom.mission.objectives = { } -- Main objective table
briefingRoom.mission.objectivesTriggersCommon = { }
$SCRIPTOBJECTIVES$


-- ===================================================================================
-- 3.4 - OBJECTIVES TRIGGERS (generated by BriefingRoom)
-- ===================================================================================

briefingRoom.mission.objectiveTriggers = { } -- Objective triggers (checks objective completion)
briefingRoom.mission.objectiveTimers = { } -- Objective timers (called every second)

function briefingRoom.mission.objectiveTimerSchedule(args, time)
  for i=1,table.count(briefingRoom.mission.objectives) do
    if briefingRoom.mission.objectiveTimers[i] ~= nil then
      briefingRoom.mission.objectiveTimers[i]()
    end
  end

  return time + 1
end

function briefingRoom.mission.destroyCallout(objectiveIndex, killedUnit, eventID, playerName)
  if killedUnit == nil or killedUnit.getName == nil  then return false end
  local unitName = killedUnit:getName()
  if not table.contains(briefingRoom.mission.objectives[objectiveIndex].unitNames, unitName) then return false end

  -- Remove the unit from the list of targets
  table.removeValue(briefingRoom.mission.objectives[objectiveIndex].unitNames, unitName)

  -- Play "target destroyed" radio message
  local soundName = "TargetDestroyed"
  local messages = { "$LANG_TARGETDESTROY1$", "$LANG_TARGETDESTROY2$", "$LANG_TARGETSHOOTDOWN1$", "$LANG_TARGETSHOOTDOWN2$" }
  local targetType = "Ground"
  local messageIndex = math.random(1, 2)
  local messageIndexOffset = 0
  if eventID == world.event.S_EVENT_CRASH and killedUnit:inAir() then
    targetType = "Air"
    messageIndexOffset = 2
  end
  if briefingRoom.eventHandler.BDASetting == "ALL" or briefingRoom.eventHandler.BDASetting == "TARGETONLY" then
    briefingRoom.radioManager.play("$LANG_COMMAND$: "..(playerName or "").." "..messages[messageIndex + messageIndexOffset], "RadioHQ"..soundName..targetType..tostring(messageIndex), math.random(1, 3))
  end

  -- Mark the objective as complete if all targets have been destroyed
  if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) < 1 then -- all target units destroyed, objective complete
    briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
  else
    briefingRoom.aircraftActivator.possibleResponsiveSpawn()
  end
  return true
end

function briefingRoom.mission.isSoftKillEvent(eventID)
  return eventID == world.event.S_EVENT_DEAD or
 eventID == world.event.S_EVENT_CRASH or
 eventID == world.event.S_EVENT_AI_ABORT_MISSION
end

function briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex)
  return briefingRoom.mission.complete or briefingRoom.mission.objectives[objectiveIndex].complete
end

function briefingRoom.mission.objectivesTriggersCommon.filterTargets(objectiveIndex, attribute, inverse)
  inverse = inverse or false
  do
    local newTargetTable = { }
    
    for _,i in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
      local unit = Unit.getByName(i)
      if unit ~= nil then
        if inverse and not unit:hasAttribute(attribute) then
          table.insert(newTargetTable, i)
        end
        if not inverse and unit:hasAttribute(attribute) then
          table.insert(newTargetTable, i)
        end 
      end
    end
  
    if table.count(newTargetTable) > 0 then
      briefingRoom.mission.objectives[objectiveIndex].unitNames = newTargetTable
      briefingRoom.mission.objectives[objectiveIndex].unitsCount = table.count(newTargetTable)
    end
  end
end

------START OF TRIGGERS TODO MOVE TO INDEPENDENT FILES---------------


function briefingRoom.mission.objectivesTriggersCommon.registerDestroyTrigger(objectiveIndex)
  table.insert(briefingRoom.mission.objectiveTriggers, function(event)

    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end

    -- Check if event is a "destruction" event
    local destructionEvent = false
    local killedUnit = event.initiator
    local playerName = nil
    if event.id == world.event.S_EVENT_KILL then
      destructionEvent = true
      killedUnit = event.target
      playerName = event.initiator.getPlayerName and event.initiator:getPlayerName() or nil
    elseif 
      briefingRoom.mission.isSoftKillEvent(event.id) or
      (event.id == world.event.S_EVENT_LAND and briefingRoom.mission.objectives[objectiveIndex].targetCategory == Unit.Category.HELICOPTER) then -- Check if parked AI Aircraft are damaged enough to be considered dead
      destructionEvent = true
    end
    -- "Landing" events are considered kills for helicopter targets

    if 
      not destructionEvent or
      killedUnit == nil or
      Object.getCategory(killedUnit) ~= Object.Category.UNIT and Object.getCategory(killedUnit) ~= Object.Category.STATIC
    then return false end

    return briefingRoom.mission.destroyCallout(objectiveIndex, killedUnit, event.id, playerName)
  end)
end

function briefingRoom.mission.objectivesTriggersCommon.registerDisableTrigger(objectiveIndex)
  table.insert(briefingRoom.mission.objectiveTriggers, function(event)
    -- Mission complete, nothing to do
    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end

    local killedUnit = event.initiator
    local playerName = nil
    if event.id == world.event.S_EVENT_KILL then
        if event.target == nil then return false end
        killedUnit = event.target
        playerName = event.initiator.getPlayerName and event.initiator:getPlayerName() or nil
    elseif  event.id == world.event.S_EVENT_HIT then -- unit was hit but not destroyed, check anyway because destroying a parked aircraft in DCS is HARD, and any aircraft with less than 90% hp left is not airworthy
        if event.target == nil then return false end
        if event.target:getCategory() ~= Object.Category.UNIT then return false end -- target was not a unit
        local life = event.target:getLife() / event.target:getLife0()
        if life > .9 then return false end -- not damaged enough
        killedUnit = event.target
    elseif briefingRoom.mission.isSoftKillEvent(event.id) then -- unit destroyed
        if event.initiator == nil then return false end
    else return false end
    return  briefingRoom.mission.destroyCallout(objectiveIndex, killedUnit, event.id, playerName)
  end)
end

function briefingRoom.mission.objectivesTriggersCommon.fireCargoNearTrigger(objectiveIndex, unitName)
   if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end
   table.removeValue(briefingRoom.mission.objectives[objectiveIndex].unitNames, unitName)
   briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_CARGODELIVERED$", "RadioPilotCargoDelivered")
    if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) < 1 then
      briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
    end
end

function briefingRoom.mission.objectivesTriggersCommon.registerKeepAliveTrigger(objectiveIndex)
  table.insert(briefingRoom.mission.objectiveTriggers, function(event)
    -- Mission complete, nothing to do
    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end

  
    -- Check if event is a "destruction" event
    local destructionEvent = false
    if event.id == world.event.S_EVENT_DEAD or event.id == world.event.S_EVENT_CRASH then destructionEvent = true end
    -- "Landing" events are considered kills for helicopter targets
    if briefingRoom.mission.objectives[objectiveIndex].targetCategory == Unit.Category.HELICOPTER and event.id == world.event.S_EVENT_LAND then destructionEvent = true end
    if not destructionEvent then return false end
  
    -- Initiator was nil
    if event.initiator == nil then return false end
    if Object.getCategory(event.initiator) ~= Object.Category.UNIT and Object.getCategory(event.initiator) ~= Object.Category.STATIC then return false end
  
    local unitName = event.initiator:getName()
    -- Destroyed unit wasn't a target
    if not table.contains(briefingRoom.mission.objectives[objectiveIndex].unitNames, unitName) then return false end
  
    -- Remove the unit from the list of targets
    table.removeValue(briefingRoom.mission.objectives[objectiveIndex].unitNames, unitName)
  
    -- Play "target destroyed" radio message
    local messages = { "$LANG_COMMAND$: $LANG_TARGETLOST1$", "$LANG_COMMAND$: $LANG_TARGETLOST2$" }
    local messageIndex = math.random(1, 2)
    local messageIndexOffset = 0
  
    if briefingRoom.eventHandler.BDASetting == "ALL" or briefingRoom.eventHandler.BDASetting == "TARGETONLY" then
      briefingRoom.radioManager.play(messages[messageIndex + messageIndexOffset], "RadioHQTargetLost", math.random(1, 3))
    end
  
    -- Mark the objective as complete if all targets have been destroyed
    if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) < 1 then -- all target units destroyed, objective failed
      briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex, true)
    end
  
    return true
  end)
end

function briefingRoom.mission.objectivesTriggersCommon.registerLandNearTrigger(objectiveIndex)
  table.insert(briefingRoom.mission.objectiveTriggers, function(event)
    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end
    if event.id ~= world.event.S_EVENT_LAND then return false end -- Not a "land" event, nothing to do
  
    if event.initiator == nil then return false end -- Initiator was nil
    if Object.getCategory(event.initiator) ~= Object.Category.UNIT then return false end -- Initiator was not an unit
    if event.initiator:getCoalition() ~= briefingRoom.playerCoalition then return false end -- Initiator was not a friendy unit

    local position = dcsExtensions.toVec2(event.initiator:getPoint()) -- get the landing unit position

    -- check if any target unit is close enough from the landing unit
    -- if so, clean the target unit ID table and mark the objective as completed
    for _,id in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
      local targetUnit = dcsExtensions.getUnitOrStatic(id)
      if targetUnit ~= nil then
        local targetPosition = dcsExtensions.toVec2(targetUnit:getPoint())
        if dcsExtensions.getDistance(position, targetPosition) < 650 then
          briefingRoom.mission.objectives[objectiveIndex].unitNames = { }
          briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
          return true
        end
      end
    end
end)

briefingRoom.mission.objectives[objectiveIndex].hideTargetCount = true
end

function briefingRoom.mission.objectivesTriggersCommon.registerFlyNearTrigger(objectiveIndex)
  table.insert(briefingRoom.mission.objectiveTimers,  function ()
    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end

  
    local players = dcsExtensions.getAllPlayers()
  
    for _,p in ipairs(players) do
      for __,u in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
        local unit = dcsExtensions.getUnitOrStatic(u)
        if unit ~= nil then
          local vec2p = dcsExtensions.toVec2(p:getPoint())
          local vec2u = dcsExtensions.toVec2(unit:getPoint())
          local distance = dcsExtensions.getDistance(vec2p, vec2u);
          
          if distance < 3704 and math.abs(vec2p.y - vec2u.y) < 609.6 and p:inAir() then -- less than 2nm away on the X/Z axis, less than 2000 feet of altitude difference
            local playername = p.getPlayerName and p:getPlayerName() or nil
            if math.random(1, 2) == 1 then
              briefingRoom.radioManager.play((playername or"$LANG_PILOT$")..": $LANG_FLYNEAR1$", "RadioPilotTargetReconned1")
            else
              briefingRoom.radioManager.play((playername or"$LANG_PILOT$")..": $LANG_FLYNEAR2$", "RadioPilotTargetReconned2")
            end
            briefingRoom.mission.objectives[objectiveIndex].unitNames = { }
            briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
            return nil
          end
        end
      end
    end
  end)
  
  briefingRoom.mission.objectives[objectiveIndex].hideTargetCount = true
end


function briefingRoom.mission.objectivesTriggersCommon.registerHoldTrigger(objectiveIndex, distanceInMeters, timeRequiredSeconds, superiorityRequired)
  superiorityRequired = superiorityRequired or false
  briefingRoom.mission.objectives[objectiveIndex].superiortyTimer = 0
  table.insert(briefingRoom.mission.objectiveTimers,  function ()
    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end
    local players = dcsExtensions.getAllPlayers()
  
    for _,p in ipairs(players) do
      local vec2p = dcsExtensions.toVec2(p:getPoint())
      for _,id in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
        local targetUnit = dcsExtensions.getUnitOrStatic(id)
        if targetUnit ~= nil then
          local targetPosition = dcsExtensions.toVec2(targetUnit:getPoint())
          local distance = dcsExtensions.getDistance(vec2p, targetPosition);
          if distance < distanceInMeters then -- less than 2nm
            if superiorityRequired then
              for __,eu in ipairs(dcsExtensions.getCoalitionUnits(briefingRoom.enemyCoalition)) do
                local evec2u = dcsExtensions.toVec2(eu:getPoint())
                local edistance = dcsExtensions.getDistance(vec2p, evec2u);
                if edistance < distanceInMeters then
                  return false
                end
              end
            end
            briefingRoom.mission.objectives[objectiveIndex].superiortyTimer = briefingRoom.mission.objectives[objectiveIndex].superiortyTimer + 1
            briefingRoom.debugPrint("Player in zone "..tostring(objectiveIndex).." for "..tostring(briefingRoom.mission.objectives[objectiveIndex].superiortyTimer).." seconds")
            if briefingRoom.mission.objectives[objectiveIndex].superiortyTimer > timeRequiredSeconds then
              briefingRoom.mission.objectives[objectiveIndex].unitNames = { }
              briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
              return nil
            end
          end
        end
      end
    end
  end)
  briefingRoom.mission.objectives[objectiveIndex].hideTargetCount = true
end

function briefingRoom.mission.objectivesTriggersCommon.escortNearTriggerlaunchMission (args)
  local objectiveIndex = args[1]
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_ESCORTSTARTREQUEST$", "RadioPilotBeginEscort")
  local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
  if unit ~= nil then
    local group = unit:getGroup()
    if group ~= nil then
      group:activate()
      briefingRoom.radioManager.play("$LANG_ESCORT$ "..objective.name..": $LANG_ESCORTAFFIRM$", "RadioEscortMoving", briefingRoom.radioManager.getAnswerDelay(), nil, nil)
    end
  end
end

function briefingRoom.mission.objectivesTriggersCommon.fireEscortNearTrigger(objectiveIndex)
   if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end
    briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_ESCORTCOMPLETE$", "RadioPilotEscortComplete")
    briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
end

function briefingRoom.mission.objectivesTriggersCommon.registerEscortNearTrigger(objectiveIndex)
  local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
  if unit ~= nil and not unit:isActive() then
    table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_ESCORTMENU$", func = briefingRoom.mission.objectivesTriggersCommon.escortNearTriggerlaunchMission, args =  {objectiveIndex}})
  end
end

function briefingRoom.mission.objectivesTriggersCommon.flyNearAndReportComplete(args)
  local objectiveIndex = args[1]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_PILOTREPORTCOMPLETE$", "RadioPilotReportComplete", math.random(1, 3))
  briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
  missionCommands.removeItemForCoalition(briefingRoom.playerCoalition, briefingRoom.mission.objectives[objectiveIndex].completeCommand)
end

function briefingRoom.mission.objectivesTriggersCommon.registerFlyNearAndReportTrigger(objectiveIndex)
  briefingRoom.mission.objectives[objectiveIndex].completeCommand = nil


  table.insert(briefingRoom.mission.objectiveTimers,  function ()
    if briefingRoom.mission.objectives[objectiveIndex].flownOver then return false end -- Objective complete, nothing to do
  
    local players = dcsExtensions.getAllPlayers()
  
    for _,p in ipairs(players) do
      for __,u in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
        local unit = dcsExtensions.getUnitOrStatic(u)
        if unit ~= nil then
          local vec2p = dcsExtensions.toVec2(p:getPoint())
          local vec2u = dcsExtensions.toVec2(unit:getPoint())
          local distance = dcsExtensions.getDistance(vec2p, vec2u);
  
          if distance < 9260 and math.abs(vec2p.y - vec2u.y) < 2438 and briefingRoom.mission.objectives[objectiveIndex].completeCommand == nil then
            local playername = p.getPlayerName and p:getPlayerName() or nil
            if math.random(1, 2) == 1 then
                briefingRoom.radioManager.play((playername or"$LANG_PILOT$").." $LANG_FLYNEAR1$", "RadioPilotTargetReconned1")
            else
                briefingRoom.radioManager.play((playername or"$LANG_PILOT$").." $LANG_FLYNEAR2$", "RadioPilotTargetReconned2")
            end
            briefingRoom.mission.objectives[objectiveIndex].unitNames = { }
            briefingRoom.mission.objectives[objectiveIndex].completeCommand = missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "$LANG_REPORTCOMPLETE$", briefingRoom.f10Menu.objectives[objectiveIndex],  briefingRoom.mission.objectivesTriggersCommon.flyNearAndReportComplete, {objectiveIndex})
          end
        end
      end
    end
  end)
end


function briefingRoom.mission.objectivesTriggersCommon.transportTroopsForcePickup(args)
  local objectiveIndex = args[1]
  if briefingRoom.mission.objectives[objectiveIndex].complete then return end
  local players = dcsExtensions.getAllPlayers()
    for _,p in ipairs(players) do
      if not p:inAir() then
      briefingRoom.debugPrint("Player on ground")
      local position = dcsExtensions.toVec2(p:getPoint())
      local collect = {}
      -- Pickup
      for _,id in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
        local targetUnit = Unit.getByName(id)
        if targetUnit ~= nil then
          local targetPosition = dcsExtensions.toVec2(targetUnit:getPoint())
          briefingRoom.debugPrint("Player distance"..dcsExtensions.getDistance(position, targetPosition))
          if dcsExtensions.getDistance(position, targetPosition) < briefingRoom.mission.objectiveDropDistanceMeters then
            table.insert(collect, id)
          end
        end
      end


      if table.count(collect) > 0 then
        briefingRoom.debugPrint("Loading "..table.count(collect).." troops")
        briefingRoom.transportManager.troopsMoveToGetIn(p:getName(), collect)
      end
    end
  end
end

function briefingRoom.mission.objectivesTriggersCommon.transportTroopsForceDrop(args)
  local objectiveIndex = args[1]
  local objectiveIndex = objectiveIndex
  if briefingRoom.mission.objectives[objectiveIndex].complete then return end
  local players = dcsExtensions.getAllPlayers()
    for _,p in ipairs(players) do
      if not p:inAir() then
        briefingRoom.debugPrint("Player on ground")
        briefingRoom.transportManager.removeTroopCargo(p:getName(), briefingRoom.mission.objectives[objectiveIndex].unitNames)
    end
  end
end

function briefingRoom.mission.objectivesTriggersCommon.fireTroopsNearTrigger(objectiveIndex, unitName)
   if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end
   table.removeValue(briefingRoom.mission.objectives[objectiveIndex].unitNames, unitName)
   briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_TROOPSDELIVERED$", "RadioPilotTroopsDelivered")
    if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) < 1 then
      briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
    end
end

function briefingRoom.mission.objectivesTriggersCommon.registerTransportTroopsTrigger(objectiveIndex)
  table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_FORCEPICKUP$", func = briefingRoom.mission.objectivesTriggersCommon.transportTroopsForcePickup, args = {objectiveIndex}})
  table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_FORCEDROP$", func =  briefingRoom.mission.objectivesTriggersCommon.transportTroopsForceDrop, args =  {objectiveIndex}})

  table.insert(briefingRoom.mission.objectiveTriggers, function(event)
    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end

    if event.id ~= world.event.S_EVENT_LAND then return false end -- Not a "land" event, nothing to do
  
    if event.initiator == nil then return false end -- Initiator was nil
    if Object.getCategory(event.initiator) ~= Object.Category.UNIT then return false end -- Initiator was not an unit
    if event.initiator:getCoalition() ~= briefingRoom.playerCoalition then return false end -- Initiator was not a friendy unit
  
    local position = dcsExtensions.toVec2(event.initiator:getPoint()) -- get the landing unit position
   
    -- Drop off
    local distanceToObjective = dcsExtensions.getDistance(briefingRoom.mission.objectives[objectiveIndex].waypoint, position);  -- Zone Pos?
    if distanceToObjective < briefingRoom.mission.objectiveDropDistanceMeters then
      local removed = briefingRoom.transportManager.removeTroopCargo(event.initiator:getName(), briefingRoom.mission.objectives[objectiveIndex].unitNames)
      for index, value in ipairs(removed) do
        table.removeValue(briefingRoom.mission.objectives[objectiveIndex].unitNames, value)
      end
      if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) < 1 then -- all target units moved or dead, objective complete
        local playername = event.initiator.getPlayerName and event.initiator:getPlayerName() or nil
        briefingRoom.radioManager.play((playername or"$LANG_PILOT$")..": $LANG_TROOPSDELIVERED$", "RadioPilotTroopsDelivered")
        briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
      end
      return true
    end
  
    local collect = {}
    -- Pickup
    for _,id in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
      local targetUnit = Unit.getByName(id)
      if targetUnit ~= nil then
        local targetPosition = dcsExtensions.toVec2(targetUnit:getPoint())
        if dcsExtensions.getDistance(position, targetPosition) < briefingRoom.mission.objectiveDropDistanceMeters then
          table.insert(collect, id)
        end
      end
    end
  
    local nonNativeTransportingAircraft = { "UH-60L" }
    if table.count(collect) > 0 and table.contains(nonNativeTransportingAircraft, event.initiator:getTypeName()) then
      briefingRoom.transportManager.troopsMoveToGetIn(event.initiator:getName(), collect)
    end
  end)
end

function briefingRoom.mission.objectivesTriggersCommon.registerCaptureLocation(objectiveIndex, objectiveLocationId)
  table.insert(briefingRoom.mission.objectiveTriggers, function(event)

    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end
    if event.id == world.event.S_EVENT_BASE_CAPTURED then

      if event.place:getID() == objectiveLocationId and event.place:getCoalition() == briefingRoom.playerCoalition then
        briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_PILOTREPORTCOMPLETE$", "RadioPilotReportComplete", math.random(1, 3))
        briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
        return true
      end
    else return false end
  end)
end


function briefingRoom.mission.objectivesTriggersCommon.registerDynamicCargoTask(objectiveIndex, airbaseName, itemName, extraCount)
  local requiredCount = -1
  table.insert(briefingRoom.mission.objectiveTimers,  function ()
    if briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex) then return false end
    local w = Airbase.getByName(airbaseName):getWarehouse()
    local count = w:getItemCount(itemName)
    if(requiredCount == -1) then
      requiredCount = count + extraCount
      briefingRoom.debugPrint("Dynamic Cargo Task started for "..itemName.." at "..airbaseName..", current: "..count.." extra count: "..extraCount.." required count: "..requiredCount, 1)
    end
    if count > requiredCount then
      briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_CARGODELIVERED$", "RadioPilotCargoDelivered")
      briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
      return nil
    end
  end)
  
  briefingRoom.mission.objectives[objectiveIndex].hideTargetCount = true
end

------END OF TRIGGERS TODO MOVE TO INDEPENDENT FILES---------------

for objIndex,obj in ipairs(briefingRoom.mission.objectives) do
  if obj.unitsCount > 0 then
    obj.unitNames = table.filter(obj.unitNames, function(o, k, i)
      local u = dcsExtensions.getUnitOrStatic(o)
      if u == nil then
        return false
      end
      return u:isExist()
    end)
  end
  if(next(obj.unitNames) == nil) then
    briefingRoom.mission.coreFunctions.completeObjective(objIndex)
  end
end

timer.scheduleFunction(briefingRoom.mission.objectiveTimerSchedule, nil, timer.getTime() + 2)
$SCRIPTOBJECTIVESTRIGGERS$

-- ===================================================================================
-- 3.5 - SCRIPT SINGLETONS (generated by BriefingRoom)
-- ===================================================================================
-- Files in here are marked with "-- BR SINGLETON FLAG" as first line
-- They should only appear once in generated scripts
$SCRIPTSINGLETONS$

-- ===================================================================================
-- 3.6 - OBJECTIVES FEATURES (generated by BriefingRoom)
-- ===================================================================================

briefingRoom.mission.objectiveFeatures = { } -- Objective features
briefingRoom.mission.objectiveFeaturesCommon = { } -- Common objective features functions
--- START OF OBJECTIVE REGISTER FEATURES-----
function briefingRoom.mission.objectiveFeaturesCommon.registerEmitRadioTransmission(objectiveIndex)
    local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
    trigger.action.radioTransmission('l10n/DEFAULT/resources/ogg/FXRadioSignal.ogg', unit:getPoint(), 0, true, 124000000, 100, "-- Morse Code --")
end

function briefingRoom.mission.objectiveFeaturesCommon.registerFireNearby(objectiveIndex)
  local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
  if unit == nil then -- no unit nor static found with the ID
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end
  local unitVec3 = unit:getPoint()
  local unitVec2 = { x = unitVec3.x, y = unitVec3.z }
  unitVec2.x = unitVec2.x + math.random(-3000, 3000)
  unitVec2.y = unitVec2.y + math.random(-3000, 3000)
  local spawnPoint = { x = unitVec2.x, y = land.getHeight(unitVec2), z = unitVec2.y }
  trigger.action.effectSmokeBig(spawnPoint, math.random(2, 3), math.random(7, 10) * 0.1)
end

function briefingRoom.mission.objectivesTriggersCommon.startAttack(args)
  local objectiveIndex = args[1]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_LAUNCHATTACKREQUEST$", "RadioPilotBeginYourAttack")
  local groupNames = dcsExtensions.getGroupNamesContaining("%-STGT%-$OBJECTIVENAME$")
  briefingRoom.debugPrint("Activating Attack group objectiveIndex: "..table.count(groupNames), 1)
  for _, value in pairs(groupNames) do
      local acGroup = Group.getByName(value) -- get the group
      if acGroup ~= nil then -- activate the group, if it exists
          acGroup:activate()
          local Start = {
              id = 'Start',
              params = {}
          }
          acGroup:getController():setCommand(Start)
          briefingRoom.debugPrint("Activating Attack group objectiveIndex: "..value, 1)
      end
  end
  briefingRoom.radioManager.play("$LANG_TROOP$: $LANG_BEGINATTACK$", "RadioOtherPilotBeginAttack")
  local idx = briefingRoom.mission.objectiveFeatures[objectiveIndex].startAttackCommandIndex
  missionCommands.removeItemForCoalition(briefingRoom.playerCoalition, briefingRoom.mission.objectives[objectiveIndex].f10Commands[idx].commandPath)
end

function briefingRoom.mission.objectiveFeaturesCommon.registerStartAttack(objectiveIndex)
  

table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_LAUNCHATTACK$", func = briefingRoom.mission.objectivesTriggersCommon.startAttack, args = {objectiveIndex}})
briefingRoom.mission.objectiveFeatures[objectiveIndex].startAttackCommandIndex = table.count(briefingRoom.mission.objectives[objectiveIndex].f10Commands)
end

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationCoordinates(args)
  local objectiveIndex = args[1]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_TARGETCOORDSREQUEST$", "RadioPilotTargetCoordinates")
  local objective = briefingRoom.mission.objectives[objectiveIndex]
    
  if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) == 0 then -- no target units left
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end
    
  local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
  if unit == nil then -- no unit nor static found with the ID
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end
    
  local unitVec3 = unit:getPoint()
  local unitVec2 = { x = unitVec3.x, y = unitVec3.z }
  local cooMessage = dcsExtensions.vec2ToStringCoordinates(unitVec2)
  briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_TARGETCOORDSAFFIRM$\n"..cooMessage, "RadioSupportTargetCoordinates", briefingRoom.radioManager.getAnswerDelay())

  local idx = briefingRoom.mission.objectiveFeatures[objectiveIndex].objRadioCommandIndex

  missionCommands.removeItemForCoalition(briefingRoom.playerCoalition, briefingRoom.mission.objectives[objectiveIndex].f10Commands[idx].commandPath)
  briefingRoom.mission.objectives[objectiveIndex].f10Commands[idx].commandPath = missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "$LANG_TARGETCOORDSMENU$.\n$LANG_TARGETCOORDSMENULAST$:\n"..cooMessage, briefingRoom.f10Menu.objectives[objectiveIndex], briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationCoordinates)
end



function briefingRoom.mission.objectiveFeaturesCommon.registerTargetDesignationCoordinates(objectiveIndex)
  table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_TARGETCOORDSMENU$", func = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationCoordinates, args =  {objectiveIndex}})
  briefingRoom.mission.objectiveFeatures[objectiveIndex].objRadioCommandIndex = table.count(briefingRoom.mission.objectives[objectiveIndex].f10Commands)
end

-- Flare

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationFlareDoFlare(args)
  trigger.action.signalFlare(args.position, trigger.flareColor.Yellow, 0)
end

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationFlare(args)
  local objectiveIndex = args[1]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_FLAIRREQUEST$", "RadioPilotMarkSelfWithFlare")
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  local objectiveFeature = briefingRoom.mission.objectiveFeatures[objectiveIndex]

  if objectiveFeature.targetDesignationFlareFlaresLeft <= 0 then
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_FLAIRNOFLAIRS$", "RadioSupportShootingFlareOut", briefingRoom.radioManager.getAnswerDelay())
    return
  end

  if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) == 0 then -- no target units left
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$:$LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end

  local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
  if unit == nil then -- no unit nor static found with the ID
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$:$LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end
  
  objectiveFeature.targetDesignationFlareFlaresLeft = objectiveFeature.targetDesignationFlareFlaresLeft - 1

  local args = { ["position"] = unit:getPoint() }

  if briefingRoom.mission.objectiveFeatures[objectiveIndex].flareInnacurate then 
    local heading = math.random(0, 359)
    local distance = math.floor(math.random(5, 20)) * 100
    args.position.x = args.position.x - math.cos(heading * DEGREES_TO_RADIANS) * distance;
    args.position.z = args.position.z - math.sin(heading * DEGREES_TO_RADIANS) * distance;
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_FLAIRAFFIRM$ "..dcsExtensions.degreesToCardinalDirection(heading).." of the Flare.", "RadioSupportShootingFlare", briefingRoom.radioManager.getAnswerDelay(), briefingRoom.mission.objectiveFeaturesCommon.targetDesignationFlareDoFlare, args)
  else
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_FLAIRAFFIRM$", "RadioSupportShootingFlare", briefingRoom.radioManager.getAnswerDelay(), briefingRoom.mission.objectiveFeaturesCommon.targetDesignationFlareDoFlare, args)
  end
end

function briefingRoom.mission.objectiveFeaturesCommon.registerTargetDesignationFlare(objectiveIndex, innacurate)
  briefingRoom.mission.objectiveFeatures[objectiveIndex].flareInnacurate = innacurate or false 
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationFlareFlaresLeft = 5
  table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_FLAIRMENU$", func = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationFlare, args =  {objectiveIndex}})
end

-- IlluminationBomb

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationIlluminationBombDoBomb(args)
  args.position.y = args.position.y + 1250 + math.random(0, 500)
  trigger.action.illuminationBomb(args.position, 100000)
end


function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationIlluminationBomb(args)
  local objectiveIndex = args[1]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_ILLUMINATIONREQUEST$", "RadioPilotDropIlluminationBomb")
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  local objectiveFeature = briefingRoom.mission.objectiveFeatures[objectiveIndex]
  -- out of bombs
  if objectiveFeature.targetDesignationIlluminationBombBombsLeft <= 0 then
    briefingRoom.radioManager.play(objective.name.." $LANG_RECON$: $LANG_ILLUMINATIONREJECT$", "RadioSupportIlluminationBombOut", briefingRoom.radioManager.getAnswerDelay())
    return
  end
  
  if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) == 0 then -- no target units left
    briefingRoom.radioManager.play(objective.name.." $LANG_RECON$:$LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end

  local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
  if unit == nil then -- no unit nor static found with the ID
    briefingRoom.radioManager.play(objective.name.." $LANG_RECON$:$LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end

  objectiveFeature.targetDesignationIlluminationBombBombsLeft = objectiveFeature.targetDesignationIlluminationBombBombsLeft - 1

  local args = { ["position"] = unit:getPoint() }
  if briefingRoom.mission.objectiveFeatures[objectiveIndex].illuminationBombInnacurate then 
    local heading = math.random(0, 359)
    local distance = math.floor(math.random(5, 20)) * 100
    args.position.x = args.position.x - math.cos(heading * DEGREES_TO_RADIANS) * distance;
    args.position.z = args.position.z - math.sin(heading * DEGREES_TO_RADIANS) * distance;
    briefingRoom.radioManager.play(objective.name.." $LANG_RECON$: $LANG_ILLUMINATIONAFFIRM$ "..dcsExtensions.degreesToCardinalDirection(heading).." of the Illumination.", "RadioSupportIlluminationBomb", briefingRoom.radioManager.getAnswerDelay(), briefingRoom.mission.objectiveFeaturesCommon.targetDesignationIlluminationBombDoBomb, args)
  else
    briefingRoom.radioManager.play(objective.name.." $LANG_RECON$: $LANG_ILLUMINATIONAFFIRM$", "RadioSupportIlluminationBomb", briefingRoom.radioManager.getAnswerDelay(), briefingRoom.mission.objectiveFeaturesCommon.targetDesignationIlluminationBombDoBomb, args)
  end
end

function briefingRoom.mission.objectiveFeaturesCommon.registerTargetDesignationIlluminationBomb(objectiveIndex, innacurate)
  briefingRoom.mission.objectiveFeatures[objectiveIndex].illuminationBombInnacurate = innacurate or false 
  -- Number of bombs available
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationIlluminationBombBombsLeft = 4
   
-- Add the command to the F10 menu
table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_ILLUMINATIONMENU$", func = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationIlluminationBomb, args =  {objectiveIndex}})

end

-- Laser

briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser = {}

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.laserWatch(args, time)
  local objectiveIndex = args[1]
  local objFeature = briefingRoom.mission.objectiveFeatures[objectiveIndex]
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  -- if lasing target is set...
  if objFeature.targetDesignationLaser.laserTarget == nil then
    return time + 1 -- next update in one second
  end

  if not objFeature.targetDesignationLaser.laserTarget:isExist() or not table.contains(objective.unitNames, objFeature.targetDesignationLaser.laserTarget:getName()) then -- target is considered complete
    briefingRoom.debugPrint("JTAC objectiveIndex: $LANG_LASERTARGETDESTROYED$", 1)
    local unit = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.setRandomTarget(objectiveIndex)
    if unit == nil then
      briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.deleteLaser(objectiveIndex)
      briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASERNOTARGET$", "RadioSupportLasingNoMoreTargets", briefingRoom.radioManager.getAnswerDelay())
      return
    end
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASERNEXTTARGET$", "RadioSupportLasingNextTarget", briefingRoom.radioManager.getAnswerDelay())
  end

  briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.updateLaserPos(objectiveIndex)
  return time + 1
end

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.turnOn(args)
  local objectiveIndex = args[1]
  local objFeature = briefingRoom.mission.objectiveFeatures[objectiveIndex]
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_LASERREQUEST$", "RadioPilotLaseTarget")

  -- already lasing something
  if objFeature.targetDesignationLaser.laserTarget ~= nil then
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASERALREADYPAINTING$ "..tostring(objFeature.targetDesignationLaser.laserCode)..".", "RadioSupportTargetLasingAlready", briefingRoom.radioManager.getAnswerDelay())
    return
  end

  -- no target units left
  local unit = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.setRandomTarget(objectiveIndex)
  if unit == nil then
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASERNOTARGETREMAINING$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end
  briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASERAFFIRM$ "..tostring(objFeature.targetDesignationLaser.laserCode)..".", "RadioSupportLasingOk", briefingRoom.radioManager.getAnswerDelay())
  missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "$LANG_LASERMENUNEWTARGET$", briefingRoom.f10Menu.objectives[objectiveIndex], briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.newTarget, {objectiveIndex})
  missionCommands.addCommandForCoalition(briefingRoom.playerCoalition, "$LANG_LASERMENUSTOP$", briefingRoom.f10Menu.objectives[objectiveIndex], briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.turnOff, {objectiveIndex})
end

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.turnOff(args)
  local objectiveIndex = args[1]
  local objFeature = briefingRoom.mission.objectiveFeatures[objectiveIndex]
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  briefingRoom.radioManager.play("$LANG_PILOT$: Terminate. Laser off.", "RadioPilotLaseTargetStop")
  -- not lasing anything
  if objFeature.targetDesignationLaser.laserTarget == nil then
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASERALREADYOFF$", "RadioSupportLasingNotLasing", briefingRoom.radioManager.getAnswerDelay())
    return
  end

  briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.deleteLaser(objectiveIndex)
  briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASEROFF$", "RadioSupportLasingStopped", briefingRoom.radioManager.getAnswerDelay())
end

-- Get new target
function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.newTarget(args)
  local objectiveIndex = args[1]
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_LASERNEWTARGET$", "RadioPilotLaseDiffrentTarget")

  -- no target units left
  local unit = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.setRandomTarget(objectiveIndex)
  if unit == nil then
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$:$LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end
  briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_LASERNEXTTARGET$", "RadioSupportLasingNextTarget", briefingRoom.radioManager.getAnswerDelay())
end
function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.updateLaserPos(objectiveIndex)
  local objFeature = briefingRoom.mission.objectiveFeatures[objectiveIndex]
  local targetPos = objFeature.targetDesignationLaser.laserTarget:getPoint()
  local targetSpeed = objFeature.targetDesignationLaser.laserTarget:getVelocity()
  -- adds a small offset so that the laser is always where the (moving) target will be, not where it is
  targetPos.x = targetPos.x + targetSpeed.x
  targetPos.y = targetPos.y + 2.0
  targetPos.z = targetPos.z + targetSpeed.z
  if objFeature.targetDesignationLaser.laserSpot == nil then
    objFeature.targetDesignationLaser.laserIRSpot = Spot.createInfraRed(objFeature.targetDesignationLaser.laserTarget, { x = math.random(-1000,1000), y = 2000, z = math.random(-1000,1000) }, targetPos)
    objFeature.targetDesignationLaser.laserSpot = Spot.createLaser(objFeature.targetDesignationLaser.laserTarget, { x = math.random(-1000,1000), y = 2000, z = math.random(-1000,1000) }, targetPos, objFeature.targetDesignationLaser.laserCode)
    briefingRoom.debugPrint("JTAC objectiveIndex: Created Laser "..objFeature.targetDesignationLaser.laserSpot:getCode()..":"..tostring(targetPos.x)..","..tostring(targetPos.y)..","..tostring(targetPos.z), 1)
  else -- spot already exists, update its position
    objFeature.targetDesignationLaser.laserIRSpot:setPoint(targetPos)
    objFeature.targetDesignationLaser.laserSpot:setPoint(targetPos)
    briefingRoom.debugPrint("JTAC objectiveIndex: Update Laser Pos "..objFeature.targetDesignationLaser.laserSpot:getCode()..":"..tostring(targetPos.x)..","..tostring(targetPos.y)..","..tostring(targetPos.z), 1)
  end

end

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.deleteLaser(objectiveIndex)
  local objFeature = briefingRoom.mission.objectiveFeatures[objectiveIndex]
  if objFeature.targetDesignationLaser.laserSpot ~= nil then
    Spot.destroy(objFeature.targetDesignationLaser.laserSpot)
    objFeature.targetDesignationLaser.laserSpot = nil
    Spot.destroy(objFeature.targetDesignationLaser.laserIRSpot)
    objFeature.targetDesignationLaser.laserIRSpot = nil
  end

  -- unset target and play radio message
  objFeature.targetDesignationLaser.laserTarget = nil
  briefingRoom.debugPrint("JTAC objectiveIndex: Deleted Laser", 1)
end

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.setRandomTarget(objectiveIndex)
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  local randomUnitName = math.randomFromHashTable(table.filter(objective.unitNames, function(o, k, i)
    local u = dcsExtensions.getUnitOrStatic(o)
    if u == nil then
      return false
    end
    return u:isExist()
  end))
  if randomUnitName == "" or randomUnitName == nil then
    return nil
  end
  local unit = dcsExtensions.getUnitOrStatic(randomUnitName)
    if unit == nil then -- no unit nor static found with the ID
      return nil
  end
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationLaser.laserTarget = unit
  briefingRoom.debugPrint("JTAC objectiveIndex: Assigned Laser Target:"..randomUnitName, 1)
  return unit
end

function briefingRoom.mission.objectiveFeaturesCommon.registerTargetDesignationLaser(objectiveIndex, laserCode)
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationLaser = { }
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationLaser.laserSpot = nil -- current laser spot
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationLaser.laserIRSpot = nil -- current laser spot
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationLaser.laserTarget = nil -- current lased target
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationLaser.laserCode = laserCode -- current lased target


-- Begin updating laser designation
timer.scheduleFunction(briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.laserWatch, {objectiveIndex}, timer.getTime() + 1)

table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_LASERMENUNEW$", func = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationLaser.turnOn, args =  {objectiveIndex}})
end


---- SMOKE

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationSmokeMarker(args)
  local objectiveIndex = args[1]
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  briefingRoom.radioManager.play("$LANG_PILOT$: $LANG_SMOKEREQUEST$", "RadioPilotMarkTargetWithSmoke")

  if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) == 0 then -- no target units left
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$:$LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
    return
  end
  
  local unit = dcsExtensions.getUnitOrStatic(briefingRoom.mission.objectives[objectiveIndex].unitNames[1])
  if unit == nil then -- no unit nor static found with the ID
      briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$:$LANG_NOTARGET$", "RadioSupportNoTarget", briefingRoom.radioManager.getAnswerDelay())
      return
  end
  
  local timeNow = timer.getAbsTime()
  
  if timeNow < briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationSmokeMarkerNextSmoke then -- Smoke not ready
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_SMOKEALREADY$", "RadioSupportTargetAlreadyMarkedWithSmoke", briefingRoom.radioManager.getAnswerDelay())
    return
  end
  
  -- Set cooldown for next smoke
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationSmokeMarkerNextSmoke = timeNow + SMOKE_DURATION
  
  -- Play radio message and setup smoke creating function
  local args = { position = unit:getPoint(), color = trigger.smokeColor.Red }
  if unit:getCoalition() == briefingRoom.playerCoalition then args.color = trigger.smokeColor.Green end
  if briefingRoom.mission.objectiveFeatures[objectiveIndex].smokeInnacurate then 
    local heading = math.random(0, 359)
    local distance = math.floor(math.random(5, 20)) * 100
    args.position.x = args.position.x - math.cos(heading * DEGREES_TO_RADIANS) * distance;
    args.position.z = args.position.z - math.sin(heading * DEGREES_TO_RADIANS) * distance;
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_SMOKEAFFIRM$ "..dcsExtensions.degreesToCardinalDirection(heading).." of the smoke.", "RadioSupportTargetMarkedWithSmoke", briefingRoom.radioManager.getAnswerDelay(), briefingRoom.mission.objectiveFeaturesCommon.targetDesignationSmokeMarkerDoSmoke, args)
  else
    briefingRoom.radioManager.play(objective.name.." $LANG_JTAC$: $LANG_SMOKEAFFIRM$", "RadioSupportTargetMarkedWithSmoke", briefingRoom.radioManager.getAnswerDelay(), briefingRoom.mission.objectiveFeaturesCommon.targetDesignationSmokeMarkerDoSmoke, args)
  end
end

function briefingRoom.mission.objectiveFeaturesCommon.targetDesignationSmokeMarkerDoSmoke(args)
  local smokePosition = args.position
  trigger.action.smoke(smokePosition, args.color)
  return nil
end

function briefingRoom.mission.objectiveFeaturesCommon.registerTargetDesignationSmoke(objectiveIndex, innacurate)
  briefingRoom.mission.objectiveFeatures[objectiveIndex].smokeInnacurate = innacurate or false 
  briefingRoom.mission.objectiveFeatures[objectiveIndex].targetDesignationSmokeMarkerNextSmoke = -999999
  -- Add the command to the F10 menu
  table.insert(briefingRoom.mission.objectives[objectiveIndex].f10Commands, {text = "$LANG_SMOKEMENU$", func = briefingRoom.mission.objectiveFeaturesCommon.targetDesignationSmokeMarker, args = {objectiveIndex}})
end


--- END OF OBJECTIVE REGISTER FEATURES-----

for i=1,table.count(briefingRoom.mission.objectives) do briefingRoom.mission.objectiveFeatures[i] = {} end
$SCRIPTOBJECTIVESFEATURES$

-- ===================================================================================
-- 3.7 - MISSION FEATURES (generated by BriefingRoom)
-- ===================================================================================

briefingRoom.mission.missionFeatures = { } -- Mission features
briefingRoom.mission.missionFeatures.groupNames = { } -- Mission features group ID
briefingRoom.mission.missionFeatures.unitNames = { } -- Mission features units ID
$SCRIPTMISSIONFEATURES$


