-- ===================================================================================
-- 3.4.1 - OBJECTIVES TRIGGERS INIT (generated by BriefingRoom)
-- ===================================================================================

for objIndex,obj in ipairs(briefingRoom.mission.objectives) do
  if obj.unitsCount > 0 then
    obj.unitNames = table.filter(obj.unitNames, function(o, k, i)
      local u = dcsExtensions.getUnitOrStatic(o)
      if u == nil then
        return false
      end
      return u:isExist()
    end)
  end
  if(next(obj.unitNames) == nil) then
    briefingRoom.mission.coreFunctions.completeObjective(objIndex)
  end
end

timer.scheduleFunction(briefingRoom.mission.objectiveTimerSchedule, nil, timer.getTime() + 2)
$SCRIPTOBJECTIVESTRIGGERS$