-- ===================================================================================
-- 3.4 - OBJECTIVES TRIGGERS (generated by BriefingRoom)
-- ===================================================================================

briefingRoom.mission.objectiveTriggersByEvent = { } -- Objective triggers by event ID
briefingRoom.mission.objectiveTimers = { } -- Objective timers (called every second)

function briefingRoom.mission.registerObjectiveEventTrigger(eventID, func)
  if briefingRoom.mission.objectiveTriggersByEvent[eventID] == nil then
    briefingRoom.mission.objectiveTriggersByEvent[eventID] = { }
  end
  table.insert(briefingRoom.mission.objectiveTriggersByEvent[eventID], func)
end

function briefingRoom.mission.objectivesTriggersCommon.rebuildObjectiveUnitNameSet(objectiveIndex)
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  objective.unitNameSet = { }
  for _, unitName in pairs(objective.unitNames) do
    objective.unitNameSet[unitName] = true
  end
end

function briefingRoom.mission.objectivesTriggersCommon.objectiveHasUnitName(objectiveIndex, unitName)
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  if objective.unitNameSet == nil then
    briefingRoom.mission.objectivesTriggersCommon.rebuildObjectiveUnitNameSet(objectiveIndex)
  end
  return objective.unitNameSet[unitName] == true
end

function briefingRoom.mission.objectivesTriggersCommon.removeObjectiveUnitName(objectiveIndex, unitName)
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  if objective.unitNameSet == nil then
    briefingRoom.mission.objectivesTriggersCommon.rebuildObjectiveUnitNameSet(objectiveIndex)
  end
  if objective.unitNameSet[unitName] ~= true then return false end

  objective.unitNameSet[unitName] = nil
  table.removeValue(objective.unitNames, unitName)
  return true
end

function briefingRoom.mission.objectivesTriggersCommon.clearObjectiveUnitNames(objectiveIndex)
  local objective = briefingRoom.mission.objectives[objectiveIndex]
  objective.unitNames = { }
  objective.unitNameSet = { }
end

function briefingRoom.mission.objectiveTimerSchedule(args, time)
  for i=1,table.count(briefingRoom.mission.objectives) do
    if briefingRoom.mission.objectiveTimers[i] ~= nil then
      if briefingRoom.mission.objectiveTimers[i]() == false then -- if the timer function returns false, stop calling it
        briefingRoom.mission.objectiveTimers[i] = nil
      end
    end
  end

  return time + 1
end

function briefingRoom.mission.destroyCallout(objectiveIndex, killedUnit, eventID, playerName)
  if killedUnit == nil or killedUnit.getName == nil  then return false end
  local unitName = killedUnit:getName()
  if not briefingRoom.mission.objectivesTriggersCommon.objectiveHasUnitName(objectiveIndex, unitName) then return false end

  -- Remove the unit from the list of targets
  briefingRoom.mission.objectivesTriggersCommon.removeObjectiveUnitName(objectiveIndex, unitName)

  -- Play "target destroyed" radio message
  local soundName = "TargetDestroyed"
  local messages = { "$LANG_TARGETDESTROY1$", "$LANG_TARGETDESTROY2$", "$LANG_TARGETSHOOTDOWN1$", "$LANG_TARGETSHOOTDOWN2$" }
  local targetType = "Ground"
  local messageIndex = math.random(1, 2)
  local messageIndexOffset = 0
  if eventID == world.event.S_EVENT_CRASH and killedUnit:inAir() then
    targetType = "Air"
    messageIndexOffset = 2
  end
  if briefingRoom.eventHandler.BDASetting == "ALL" or briefingRoom.eventHandler.BDASetting == "TARGETONLY" then
    briefingRoom.radioManager.play("$LANG_COMMAND$: "..(playerName or "").." "..messages[messageIndex + messageIndexOffset], "RadioHQ"..soundName..targetType..tostring(messageIndex), math.random(1, 3))
  end

  -- Mark the objective as complete if all targets have been destroyed
  if table.count(briefingRoom.mission.objectives[objectiveIndex].unitNames) < 1 then -- all target units destroyed, objective complete
    briefingRoom.mission.coreFunctions.completeObjective(objectiveIndex)
  else
    briefingRoom.aircraftActivator.possibleResponsiveSpawn()
  end
  return true
end

function briefingRoom.mission.isSoftKillEvent(eventID)
  return eventID == world.event.S_EVENT_DEAD or
 eventID == world.event.S_EVENT_CRASH or
 eventID == world.event.S_EVENT_AI_ABORT_MISSION
end

function briefingRoom.mission.objectivesTriggersCommon.isMissionOrObjectiveComplete(objectiveIndex)
  return briefingRoom.mission.complete or briefingRoom.mission.objectives[objectiveIndex].complete
end

function briefingRoom.mission.objectivesTriggersCommon.filterTargets(objectiveIndex, attribute, inverse)
  inverse = inverse or false
  do
    local newTargetTable = { }
    
    for _,i in ipairs(briefingRoom.mission.objectives[objectiveIndex].unitNames) do
      local unit = Unit.getByName(i)
      if unit ~= nil then
        if inverse and not unit:hasAttribute(attribute) then
          table.insert(newTargetTable, i)
        end
        if not inverse and unit:hasAttribute(attribute) then
          table.insert(newTargetTable, i)
        end 
      end
    end
  
    if table.count(newTargetTable) > 0 then
      briefingRoom.mission.objectives[objectiveIndex].unitNames = newTargetTable
      briefingRoom.mission.objectives[objectiveIndex].unitsCount = table.count(newTargetTable)
      briefingRoom.mission.objectivesTriggersCommon.rebuildObjectiveUnitNameSet(objectiveIndex)
    end
  end
end