-- ===================================================================================
-- 3.7 - MISSION FEATURES (generated by BriefingRoom)
-- ===================================================================================

briefingRoom.mission.missionFeatures = { } -- Mission features
briefingRoom.mission.missionFeatures.groupNames = { } -- Mission features group ID
briefingRoom.mission.missionFeatures.unitNames = { } -- Mission features units ID
$SCRIPTMISSIONFEATURES$