-- ===================================================================================
-- 3.3 - OBJECTIVES TABLES (generated by BriefingRoom)
-- ===================================================================================

briefingRoom.mission.objectives = { } -- Main objective table
briefingRoom.mission.objectivesTriggersCommon = { }
$SCRIPTOBJECTIVES$
